### ISSUE TITLE
Issue with branch 1-3-stable.

### ISSUE THREAD

**Issue by newtechfusion** [jipiboily/spree_multi_lingual#30]
When I add :
gem 'spree_multi_lingual', :git => "git@github.com:jipiboily/spree_multi_lingual.git"
gem 'globalize3', :git => 'git://github.com/svenfuchs/globalize3.git'
and bundle install it is giving the following error::
Could not find gem 'globalize3 (= 0.2.0) ruby', which is required by gem 'spree_multi_lingual (>= 0) ruby', in any of the sources.

Also if I remove :git => 'git://github.com/svenfuchs/globalize3.git' and do rails g spree_multi_lingual:install its giving error like ::
/home/ntf/.rvm/gems/ruby-1.8.7-p371/gems/polyglot-0.3.3/lib/polyglot.rb:63:in `polyglot_original_require': /home/ntf/.rvm/gems/ruby-1.8.7-p371/bundler/gems/spree_multi_lingual-6d332ef67094/lib/spree_multi_lingual/translates_with_accessors.rb:50: syntax error, unexpected ':', expecting kEND (SyntaxError)
...  globalize_accessors locales: SpreeMultiLingual.languages, ...
                              ^
/home/ntf/.rvm/gems/ruby-1.8.7-p371/bundler/gems/spree_multi_lingual-6d332ef67094/lib/spree_multi_lingual/translates_with_accessors.rb:50: syntax error, unexpected ':', expecting '='
...Lingual.languages, attributes: params.to_a if accessors
                              ^
    from /home/ntf/.rvm/gems/ruby-1.8.7-p371/gems/polyglot-0.3.3/lib/polyglot.rb:63:in`require'
    from /home/ntf/.rvm/gems/ruby-1.8.7-p371/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
    from /home/ntf/.rvm/gems/ruby-1.8.7-p371/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:236:in`load_dependency'
    from /home/ntf/.rvm/gems/ruby-1.8.7-p371/gems/activesupport-3.2.11/lib/active_support/dependencies.rb:251:in `require'
    from /home/ntf/.rvm/gems/ruby-1.8.7-p371/bundler/gems/spree_multi_lingual-6d332ef67094/lib/spree_multi_lingual.rb:6
    from /home/ntf/.rvm/gems/ruby-1.8.7-p371@global/gems/bundler-1.2.3/lib/bundler/runtime.rb:68:in`require'
    from /home/ntf/.rvm/gems/ruby-1.8.7-p371@global/gems/bundler-1.2.3/lib/bundler/runtime.rb:68:in `require'
    from /home/ntf/.rvm/gems/ruby-1.8.7-p371@global/gems/bundler-1.2.3/lib/bundler/runtime.rb:66:in`each'
    from /home/ntf/.rvm/gems/ruby-1.8.7-p371@global/gems/bundler-1.2.3/lib/bundler/runtime.rb:66:in `require'
    from /home/ntf/.rvm/gems/ruby-1.8.7-p371@global/gems/bundler-1.2.3/lib/bundler/runtime.rb:55:in`each'
    from /home/ntf/.rvm/gems/ruby-1.8.7-p371@global/gems/bundler-1.2.3/lib/bundler/runtime.rb:55:in `require'
    from /home/ntf/.rvm/gems/ruby-1.8.7-p371@global/gems/bundler-1.2.3/lib/bundler.rb:128:in`require'
    from /home/ntf/SPREE_WITH_RAILS/blackpearl1.2/config/application.rb:7
    from /home/ntf/.rvm/gems/ruby-1.8.7-p371/gems/railties-3.2.11/lib/rails/commands.rb:24:in `require'
    from /home/ntf/.rvm/gems/ruby-1.8.7-p371/gems/railties-3.2.11/lib/rails/commands.rb:24
    from script/rails:6:in`require'
    from script/rails:6

**Comment by MatthieuBarthel** [comment]
I just had this error too, it looks like the last version of Globalize includes the patch that was needed in master, so just update your Gemfile:

```
gem 'globalize3'
```

Unfortunately, I have another issue, running **bundle update** doesn't work (frozen on Fetching gem metadata from https://rubygems.org/..)

**Comment by MatthieuBarthel** [comment]
Sorry my stucked bundler issue was not related to spree_multi_lingual, it was my fault ;)

**Comment by ghost** [comment]
seems not to be working with latest Spree Core version 1.3.2

Bundler could not find compatible versions for gem "spree_core":
  In Gemfile:
    spree_multi_lingual (>= 0) ruby depends on
      spree_core (~> 1.1.0) ruby

```
spree (= 1.3.2) ruby depends on
  spree_core (1.3.2)
```

**Comment by MatthieuBarthel** [comment]
Did you specify the 1-3-stable branch ? For me spree_multi_lingual works just fine.

```
gem 'spree_multi_lingual', git: "git@github.com:jipiboily/spree_multi_lingual.git", branch: '1-3-stable'
```

**Comment by ghost** [comment]
no of course ... thanks a lot  re-bundled , no issue anymore ... thanks a lot !
